export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_IN = 'SIGN_IN'

export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const UPDATE_USER_IP = 'UPDATE_USER_IP'
export const USER_EVENT_RECEIVED = 'USER_EVENT_RECEIVED'
export const USER_EVENT_UNSUBSCRIBED = 'USER_EVENT_UNSUBSCRIBED'

export const SET_EVENTS_FILTER = 'SET_EVENTS_FILTER'
export const SET_EVENTS_FILTER_PARAMS = 'SET_EVENTS_FILTER_PARAMS'

export const PUBLISH_STATUS_REQUEST = 'PUBLISH_STATUS_REQUEST'
export const PUBLISH_STATUS_SUCCESS = 'PUBLISH_STATUS_SUCCESS'
export const PUBLISH_STATUS_ERROR = 'PUBLISH_STATUS_ERROR'

export const USER_PHOTOS_SUBSCRIBED = 'USER_PHOTOS_SUBSCRIBED'
export const USER_PHOTOS_RECEIVED = 'USER_PHOTOS_RECEIVED'
export const USER_PHOTOS_UNSUBSCRIBED = 'USER_PHOTOS_UNSUBSCRIBED'

export const FETCH_FEED_REQUEST = 'FETCH_FEED_REQUEST'
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS'
export const FETCH_FEED_ERROR = 'FETCH_FEED_ERROR'

export const FETCH_PHOTOS_REQUEST = 'FETCH_PHOTOS_REQUEST'
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS'
export const FETCH_PHOTOS_ERROR = 'FETCH_PHOTOS_ERROR'

export const ADD_FAVORITE_EVENT = 'ADD_FAVORITE_EVENT'
export const REMOVE_FAVORITE_EVENT = 'REMOVE_FAVORITE_EVENT'

export const EVENT_ATTENDEES_RECEIVED = 'EVENT_ATTENDEES_RECEIVED'
export const EVENT_ATTENDEES_UNSUBSCRIBED = 'EVENT_ATTENDEES_UNSUBSCRIBED'

export const SET_FCM_TOKEN = 'SET_FCM_TOKEN'
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const PROFILE_RECEIVED = 'PROFILE_RECEIVED'

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR'

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_ERROR = 'FOLLOW_USER_ERROR'

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST'
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'
export const UNFOLLOW_USER_ERROR = 'UNFOLLOW_USER_ERROR'

export const FETCH_FOLLOWING_REQUEST = 'FETCH_FOLLOWING_REQUEST'
export const FETCH_FOLLOWING_SUCCESS = 'FETCH_FOLLOWING_SUCCESS'
export const FETCH_FOLLOWING_ERROR = 'FETCH_FOLLOWING_ERROR'

export const FETCH_FOLLOWERS_REQUEST = 'FETCH_FOLLOWERS_REQUEST'
export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS'
export const FETCH_FOLLOWERS_ERROR = 'FETCH_FOLLOWERS_ERROR'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR'

export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'
export const CREATE_CHAT_ERROR = 'CREATE_CHAT_ERROR'
export const CLEAR_CHAT = 'CLEAR_CHAT'
export const CLEAR_CHAT_ERROR = 'CLEAR_CHAT_ERROR'

export const SEND_CHAT_MSG_REQUEST = 'SEND_CHAT_MSG_REQUEST'
export const SEND_CHAT_MSG_SUCCESS = 'SEND_CHAT_MSG_SUCCESS'
export const SEND_CHAT_MSG_ERROR = 'SEND_CHAT_MSG_ERROR'

export const FETCH_CHAT_GROUPS_REQUEST = 'FETCH_CHAT_GROUPS_REQUEST'
export const FETCH_CHAT_GROUPS_SUCCESS = 'FETCH_CHAT_GROUPS_SUCCESS'
export const FETCH_CHAT_GROUPS_ERROR = 'FETCH_CHAT_GROUPS_ERROR'

export const FETCH_CHAT_MESSAGES_REQUEST = 'FETCH_CHAT_MESSAGES_REQUEST'
export const FETCH_CHAT_MESSAGES_SUCCESS = 'FETCH_CHAT_MESSAGES_SUCCESS'
export const FETCH_CHAT_MESSAGES_ERROR = 'FETCH_CHAT_MESSAGES_ERROR'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const USER_ID_UPLOAD_REQUEST = 'USER_ID_UPLOAD_REQUEST'
export const USER_ID_UPLOAD_SUCCESS = 'USER_ID_UPLOAD_SUCCESS'
export const USER_ID_UPLOAD_ERROR = 'USER_ID_UPLOAD_ERROR'

export const USER_PREFERENCES_RECEIVED = 'USER_PREFERENCES_RECEIVED'
export const USER_PREFERENCES_UNSUBSCRIBED= 'USER_PREFERENCES_UNSUBSCRIBED'
export const USER_NOTIF_UPDATED = 'USER_NOTIFICATION_UPDATED'
export const USER_NOTIF_ERROR = 'USER_PREFERENCES_ERROR'

export const SET_NEW_GEO_LOCATION = 'SET_NEW_GEO_LOCATION'
export const GEO_LOCATION_ERROR = 'GEO_LOCATION_ERROR'

export const ATTEND_EVENT_REQUEST = 'ATTEND_EVENT_REQUEST'
export const ATTEND_EVENT_SUCCESS = 'ATTEND_EVENT_SUCCESS'
export const ATTEND_EVENT_ERROR = 'ATTEND_EVENT_ERROR'

export const WAIVE_EVENT_SPOT_REQUEST = 'WAIVE_EVENT_SPOT_REQUEST'
export const WAIVE_EVENT_SPOT_SUCCESS = 'WAIVE_EVENT_SPOT_SUCCESS'
export const WAIVE_EVENT_SPOT_ERROR = 'WAIVE_EVENT_SPOT_ERROR'

export const SUSPEND_EVENT_REQUEST = 'SUSPEND_EVENT_REQUEST'
export const SUSPEND_EVENT_SUCCESS = 'SUSPEND_EVENT_SUCCESS'
export const SUSPEND_EVENT_ERROR = 'SUSPEND_EVENT_ERROR'

export const EVENT_PUSHING = 'EVENT_PUSHING'
export const EVENT_PUSHING_SUCCESS = 'EVENT_PUSHING_SUCCESS'
export const EVENT_PUSHING_ERROR = 'EVENT_PUSHING_ERROR'

export const EVENT_RATE_REQUEST = 'EVENT_RATE_REQUEST'
export const EVENT_RATE_SUCCESS = 'EVENT_RATE_SUCCESS'
export const EVENT_RATE_ERROR = 'EVENT_RATE_ERROR'

export const CLEAR_EVENT = 'CLEAR_EVENT'

export const EVENT_NEAR = 'EVENT_NEAR'
export const EVENT_FAR = 'EVENT_FAR'

export const EVENT_FETCH_REQUEST = 'EVENT_FETCH_REQUEST'
export const EVENT_FETCH_SUCCESS = 'EVENT_FETCH_SUCCESS'
export const EVENT_TICKETS_FETCH_SUCCESS = 'EVENT_TICKETS_FETCH_SUCCESS'

export const BANNER_NEAR = 'BANNER_NEAR'
export const BANNER_FAR = 'BANNER_FAR'

export const BANNER_FETCH_REQUEST = 'BANNER_FETCH_REQUEST'
export const BANNER_FETCH_SUCCESS = 'BANNER_FETCH_SUCCESS'
export const BANNER_FETCH_ERROR = 'BANNER_FETCH_ERROR'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_ERROR = 'CHECKOUT_ERROR'
export const CLEAR_CHECKOUT = 'CLEAR_CHECKOUT'

export const ADD_PAYMENT_CARD_REQUEST = 'ADD_PAYMENT_CARD_REQUEST'
export const ADD_PAYMENT_CARD_SUCCESS = 'ADD_PAYMENT_CARD_SUCCESS'
export const ADD_PAYMENT_CARD_ERROR = 'ADD_PAYMENT_CARD_ERROR'

export const REMOVE_PAYMENT_CARD_REQUEST = 'REMOVE_PAYMENT_CARD_REQUEST'
export const REMOVE_PAYMENT_CARD_SUCCESS = 'REMOVE_PAYMENT_CARD_SUCCESS'
export const REMOVE_PAYMENT_CARD_ERROR = 'REMOVE_PAYMENT_CARD_ERROR'

export const PAYMENT_CARD_RECEIVED = 'PAYMENT_CARD_RECEIVED'
export const CLEAR_PAYMENT_CARD_ERROR = 'CLEAR_PAYMENT_CARD_ERROR'

export const BANK_ACCOUNT_RECEIVED = 'BANK_ACCOUNT_RECEIVED'

export const ADD_BANK_ACCOUNT_REQUEST = 'ADD_BANK_ACCOUNT_REQUEST'
export const ADD_BANK_ACCOUNT_SUCCESS = 'ADD_BANK_ACCOUNT_SUCCESS'
export const ADD_BANK_ACCOUNT_ERROR = 'ADD_BANK_ACCOUNT_ERROR'
export const CLEAR_BANK_ACCOUNT_ERROR = 'CLEAR_BANK_ACCOUNT_ERROR'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'