import I18n from '../i18n';

export const PlaceTypes = [
  {id: 'house', 
    name: I18n.t('placeTypes.house'), 
    image: require('../../assets/images/place-types/house.jpg')
  },
  {id: 'outdoors', name: I18n.t('placeTypes.outdoors'), image: require('../../assets/images/place-types/outdoors.jpg')},
  {id: 'rooftop', name: I18n.t('placeTypes.rooftop'), image: require('../../assets/images/place-types/rooftop.jpg')},
  {id: 'shop', name: I18n.t('placeTypes.shop'), image: require('../../assets/images/place-types/shop.jpg')},
  {id: 'castle', name: I18n.t('placeTypes.castle'), image: require('../../assets/images/place-types/castle.jpg')},
  {id: 'club', name: I18n.t('placeTypes.club'), image: require('../../assets/images/place-types/club.jpg')},
  {id: 'bar', name: I18n.t('placeTypes.bar'), image: require('../../assets/images/place-types/bar.jpg')},
  {id: 'city', name: I18n.t('placeTypes.city'), image: require('../../assets/images/place-types/city.jpg')},
  {id: 'museum', name: I18n.t('placeTypes.museum'), image: require('../../assets/images/place-types/museum.jpg')},
  {id: 'boat', name: I18n.t('placeTypes.boat'), image: require('../../assets/images/place-types/boat.jpg')},
  {id: 'gallery', name: I18n.t('placeTypes.gallery'), image: require('../../assets/images/place-types/gallery.jpg')},
]

export const Categories = [
  {id: 'party', 
    name: I18n.t('categories.party'), 
    isActive: true, 
    coverImg: require('../../assets/images/categories/party.png'),
  },
  {id: 'work', 
    name: I18n.t('categories.work'), 
    isActive: true, 
    coverImg: require('../../assets/images/categories/work.png'),
  },
  {id: 'food', 
    name: I18n.t('categories.food'), 
    isActive: true, 
    coverImg: require('../../assets/images/categories/food.png'),
  },
  {
    id: 'culture',
    name: I18n.t('categories.culture'),
    isActive: true,
    coverImg: require('../../assets/images/categories/culture.jpg'),
  },
  {id: 'sport', name: I18n.t('categories.sport'), isActive: true, coverImg: require('../../assets/images/categories/sport.png'),},
  {
    id: 'wellness',
    name: I18n.t('categories.wellness'),
    isActive: true,
    coverImg: require('../../assets/images/categories/wellness.png'),
  },
  {
    id: 'excursion',
    name: I18n.t('categories.excursion'),
    isActive: true,
    coverImg: require('../../assets/images/categories/excursion.png'),
  },
  {
    id: 'fashion',
    name: I18n.t('categories.fashion'),
    isActive: true,
    coverImg: require('../../assets/images/categories/fashion.png'),
  },
  {id: 'gaming', 
    name: I18n.t('categories.gaming'), isActive: true, 
    coverImg: require('../../assets/images/categories/gaming.png'),
  },
  {id: 'happy_hour', 
    name: I18n.t('categories.happyHour'), 
    isActive: true, 
    coverImg: require('../../assets/images/categories/happy_hours.png'),
  },
]




export const Tags = [
  {id: 'Party', 
    name: I18n.t('tags.party'), 
    isActive: true,
  },
  {id: 'Culture', 
    name: I18n.t('tags.culture'), 
    isActive: true,
  },
  {id: 'Work', 
    name: I18n.t('tags.work'), 
    isActive: true,
  },
  {id: 'Business', 
    name: I18n.t('tags.business'), 
    isActive: true,
  },
  {id: 'Sport', 
    name: I18n.t('tags.sport'), 
    isActive: true,
  },
  {id: 'Food', 
    name: I18n.t('tags.food'), 
    isActive: true,
  },
  {id: 'Drink', 
    name: I18n.t('tags.drink'), 
    isActive: true,
  },
  {id: 'Wellness', 
    name: I18n.t('tags.wellness'), 
    isActive: true,
  },
  {id: 'Excursion', 
    name: I18n.t('tags.excursion'), 
    isActive: true,
  },
  {id: 'Fashion', 
    name: I18n.t('tags.fashion'), 
    isActive: true,
  },
  {id: 'Gaming', 
    name: I18n.t('tags.gaming'), 
    isActive: true,
  },
  {id: 'Happy', 
    name: I18n.t('tags.happy'), 
    isActive: true,
  },
  {id: 'Male', 
    name: I18n.t('tags.male'), 
    isActive: true,
  },
  {id: 'Female', 
    name: I18n.t('tags.female'), 
    isActive: true,
  },
  {id: 'Shopping', 
    name: I18n.t('tags.shopping'), 
    isActive: true,
  },
  {id: 'City', 
    name: I18n.t('tags.city'), 
    isActive: true,
  },
  {id: 'Photo', 
    name: I18n.t('tags.photo'), 
    isActive: true,
  },
  {id: 'Video', 
    name: I18n.t('tags.video'), 
    isActive: true,
  },
  {id: 'Song', 
    name: I18n.t('tags.song'), 
    isActive: true,
  },
  {id: 'Event', 
    name: I18n.t('tags.event'), 
    isActive: true,
  },
]


