export const TEST_CONTACTS = [
  {
    'id': '913850cc-cb5e-4182-b6eb-004eeec7c676',
    'first_name': 'Kimmie',
    'last_name': 'Caldaro',
    'profile_img': 'https://robohash.org/sintapariatur.jpg?size=50x50&set=set1',
    'username': 'kcaldaro0',
  },
  {
    'id': '4d1c09c7-a384-4443-92ff-97a38e448af6',
    'first_name': 'Maurise',
    'last_name': 'Southey',
    'profile_img': 'https://robohash.org/quocorruptivoluptatem.bmp?size=50x50&set=set1',
    'username': 'msouthey1',
  },
  {
    'id': 'fe5d5862-195a-4f0c-a45e-e9e206d993c6',
    'first_name': 'Cleavland',
    'last_name': 'Brettor',
    'profile_img': 'https://robohash.org/voluptatemutvero.png?size=50x50&set=set1',
    'username': 'cbrettor2',
  },
  {
    'id': '4d08ab31-4d25-49a2-ac1a-08966d44d616',
    'first_name': 'Patrizius',
    'last_name': 'Gooch',
    'profile_img': 'https://robohash.org/eosfugaut.bmp?size=50x50&set=set1',
    'username': 'pgooch3',
  },
  {
    'id': 'e1da3219-0cb6-466c-88cd-b730c4951396',
    'first_name': 'Marion',
    'last_name': 'Volant',
    'profile_img': 'https://robohash.org/suntdolorumest.jpg?size=50x50&set=set1',
    'username': 'mvolant4',
  },
  {
    'id': 'a24907a9-0a57-4068-876d-e380d2409fe0',
    'first_name': 'Gilles',
    'last_name': 'Tapsell',
    'profile_img': 'https://robohash.org/quoofficiisomnis.png?size=50x50&set=set1',
    'username': 'gtapsell5',
  },
  {
    'id': 'e00dd0ee-e95b-4842-9cfd-66c82184e268',
    'first_name': 'Sherwood',
    'last_name': 'Spivie',
    'profile_img': 'https://robohash.org/aliquamdoloret.bmp?size=50x50&set=set1',
    'username': 'sspivie6',
  },
  {
    'id': 'df7cc34f-673c-4b33-a168-4f2515d936aa',
    'first_name': 'Maribelle',
    'last_name': 'Pantin',
    'profile_img': 'https://robohash.org/voluptasveritatisquia.jpg?size=50x50&set=set1',
    'username': 'mpantin7',
  },
  {
    'id': '15758e82-4c31-44c2-ad5e-5ef6968ebef6',
    'first_name': 'Maudie',
    'last_name': 'Melarkey',
    'profile_img': 'https://robohash.org/doloresnamat.jpg?size=50x50&set=set1',
    'username': 'mmelarkey8',
  },
  {
    'id': '918f4864-6062-4d5f-9209-501cf15c5929',
    'first_name': 'Christa',
    'last_name': 'Moretto',
    'profile_img': 'https://robohash.org/quiavoluptasut.png?size=50x50&set=set1',
    'username': 'cmoretto9',
  },
  {
    'id': '3ad64ebf-7b54-4334-ae89-ec5e9d215ded',
    'first_name': 'Braden',
    'last_name': 'Filipic',
    'profile_img': 'https://robohash.org/maioresdeseruntvoluptatum.bmp?size=50x50&set=set1',
    'username': 'bfilipica',
  },
  {
    'id': '055488bd-be56-4108-bc5f-20007e976ff1',
    'first_name': 'Leanora',
    'last_name': 'Reitenbach',
    'profile_img': 'https://robohash.org/quoautiure.png?size=50x50&set=set1',
    'username': 'lreitenbachb',
  },
  {
    'id': '40085de5-512d-4f2a-a3d5-a6a29851cfbd',
    'first_name': 'Reinhold',
    'last_name': 'McGraw',
    'profile_img': 'https://robohash.org/molestiaeestexplicabo.png?size=50x50&set=set1',
    'username': 'rmcgrawc',
  },
  {
    'id': '710428b7-45c2-4bee-abfb-ac9d22f68cd9',
    'first_name': 'Enrichetta',
    'last_name': 'Simkovich',
    'profile_img': 'https://robohash.org/quiainaut.png?size=50x50&set=set1',
    'username': 'esimkovichd',
  },
  {
    'id': '50663567-f3c5-4761-ac7a-77a892f8a962',
    'first_name': 'Ariella',
    'last_name': 'Chastenet',
    'profile_img': 'https://robohash.org/nemoquisnostrum.bmp?size=50x50&set=set1',
    'username': 'achastenete',
  },
  {
    'id': '839a0786-9943-40c1-9096-cf871ed1cd21',
    'first_name': 'Wilt',
    'last_name': 'Taggert',
    'profile_img': 'https://robohash.org/etdolorumcum.png?size=50x50&set=set1',
    'username': 'wtaggertf',
  },
  {
    'id': 'ec53c965-d707-4dbd-8d42-89b7b85b3f46',
    'first_name': 'Ethelyn',
    'last_name': 'Patterfield',
    'profile_img': 'https://robohash.org/commodifugiatconsequuntur.jpg?size=50x50&set=set1',
    'username': 'epatterfieldg',
  },
  {
    'id': '1b2aa01c-1cde-4324-ab1f-1ea282e4924b',
    'first_name': 'Lydon',
    'last_name': 'Scole',
    'profile_img': 'https://robohash.org/expeditaaliquamdolor.png?size=50x50&set=set1',
    'username': 'lscoleh',
  },
  {
    'id': '9ba19d54-8dd3-4314-b582-1e9a94bf0336',
    'first_name': 'Wendie',
    'last_name': 'Alleway',
    'profile_img': 'https://robohash.org/atquevelitreprehenderit.bmp?size=50x50&set=set1',
    'username': 'wallewayi',
  },
  {
    'id': 'ae5f4e04-8e00-45e7-bfe1-89fe52dfb9be',
    'first_name': 'Shaylyn',
    'last_name': 'MacCurley',
    'profile_img': 'https://robohash.org/suntquisquameum.png?size=50x50&set=set1',
    'username': 'smaccurleyj',
  },
  {
    'id': '5faf4adb-1080-4d96-a0ff-2a9bd293261c',
    'first_name': 'Geralda',
    'last_name': 'Veysey',
    'profile_img': 'https://robohash.org/aperiamdoloribussit.bmp?size=50x50&set=set1',
    'username': 'gveyseyk',
  },
  {
    'id': '1b74755c-805f-4b38-8db5-ce161e244869',
    'first_name': 'Grissel',
    'last_name': 'Obispo',
    'profile_img': 'https://robohash.org/quishicnon.bmp?size=50x50&set=set1',
    'username': 'gobispol',
  },
  {
    'id': 'ad702b1f-99ae-40f5-81f5-604ea4ca50e7',
    'first_name': 'Kev',
    'last_name': 'Goneau',
    'profile_img': 'https://robohash.org/siteosest.jpg?size=50x50&set=set1',
    'username': 'kgoneaum',
  },
]

export const TEST_EVENTS = {
  '-KjswmOpMHBlz8Sd_mjt': {
    'address': 'Irarrazaval 4200',
    'coverImgUrl': 'https://zone1-ibizaspotlightsl.netdna-ssl.com/sites/default/files/promoter-images/91014/coupon-1397081742.jpg',
    'lat': -33.452832,
    'lon': -70.58927,
    'name': 'Party fest',
    'ownerId': 'd18kHzaIJKNCPHVYlRu8xnEH8q33',
    'type': 'party',
  },
  '-KjswmOti82BRmnq8g-0': {
    'address': 'Irarrazaval 4200',
    'coverImgUrl': 'https://www.trabajemos.cl/wp-content/uploads/2016/01/AfterOfficeLogo.jpg',
    'lat': -33.445218,
    'lon': -70.604505,
    'name': 'After Office Party',
    'ownerId': 'd18kHzaIJKNCPHVYlRu8xnEH8q33',
    'type': 'work',
  },
  '-KjswmOuSfwqZ2aNiT3Q': {
    'address': 'Irarrazaval 4200',
    'coverImgUrl': 'https://static2.tripoto.com/media/transfer/img/OgData/1467292462_full_moon_beach_party_at_koh_pagnan_in_koh_samui_thailand30_june_15.jpg',
    'lat': -33.4350366,
    'lon': -70.6343891,
    'name': 'Beach Party',
    'ownerId': 'd18kHzaIJKNCPHVYlRu8xnEH8q33',
    'type': 'party',
  },
  '-KjswmOuSfwqZ2aNiT3R': {
    'address': 'Irarrazaval 4200',
    'coverImgUrl': 'https://www.tomorrowland.com/src/Frontend/Themes/tomorrowland/Core/Layout/images/timeline/2013-1.jpg',
    'lat': -33.432113,
    'lon': -70.635816,
    'name': 'Tomorrowland',
    'ownerId': 'd18kHzaIJKNCPHVYlRu8xnEH8q33',
    'type': 'party',
  },
  '-KjswmOv_CwtgP2BfIVY': {
    'address': 'Irarrazaval 4200',
    'coverImgUrl': 'https://cdn-1-www.lollapalooza.com/wp/wp-content/uploads/2015/12/LOL16_BlogHeader_4thDay.jpg',
    'lat': -33.436769,
    'lon': -70.630645,
    'name': 'Lollapalooza',
    'ownerId': 'd18kHzaIJKNCPHVYlRu8xnEH8q33',
    'type': 'party',
  },
  'france1': {
    'address': 'Irarrazaval 4200',
    'coverImgUrl': 'https://www.tomorrowland.com/src/Frontend/Themes/tomorrowland/Core/Layout/images/timeline/2013-1.jpg',
    'lat': 44.831922,
    'lon': -0.573337,
    'name': 'Tomorrowland Bordeaux',
    'ownerId': 'd18kHzaIJKNCPHVYlRu8xnEH8q33',
    'type': 'party',
  },
  'france2': {
    'address': 'Irarrazaval 4200',
    'coverImgUrl': 'https://cdn-1-www.lollapalooza.com/wp/wp-content/uploads/2015/12/LOL16_BlogHeader_4thDay.jpg',
    'lat': 44.830796,
    'lon': -0.571567,
    'name': 'Lollapalooza Bordeaux',
    'ownerId': 'd18kHzaIJKNCPHVYlRu8xnEH8q33',
    'type': 'party',
  },
}

export const TEST_CHATS = [
  {
    'id': 1,
    'username': 'cschoffel0',
    'first_name': 'Cody',
    'last_name': 'Schoffel',
    'profile_img': 'https://robohash.org/inblanditiisvoluptatem.png?size=128x128&set=set1',
    'comment': 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    'timestamp': '1488859280',
  }, {
    'id': 2,
    'username': 'jglendenning1',
    'first_name': 'Joellen',
    'last_name': 'Glendenning',
    'profile_img': 'https://robohash.org/estminusperferendis.png?size=128x128&set=set1',
    'comment': 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
    'timestamp': '1487517685',
  }, {
    'id': 3,
    'username': 'cmitchard2',
    'first_name': 'Cyb',
    'last_name': 'Mitchard',
    'profile_img': 'https://robohash.org/sitquidemveniam.png?size=128x128&set=set1',
    'comment': 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
    'timestamp': '1487356090',
  }, {
    'id': 4,
    'username': 'pstiles3',
    'first_name': 'Paige',
    'last_name': 'Stiles',
    'profile_img': 'https://robohash.org/officiaatquidem.png?size=128x128&set=set1',
    'comment': 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.',
    'timestamp': '1481415160',
  }, {
    'id': 5,
    'username': 'framirez4',
    'first_name': 'Federica',
    'last_name': 'Ramirez',
    'profile_img': 'https://robohash.org/reprehenderitmollitiavitae.png?size=128x128&set=set1',
    'comment': 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',
    'timestamp': '1491730093',
  }, {
    'id': 6,
    'username': 'gbebbington5',
    'first_name': 'Glenda',
    'last_name': 'Bebbington',
    'profile_img': 'https://robohash.org/ipsamsintcumque.png?size=128x128&set=set1',
    'comment': 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
    'timestamp': '1489871435',
  }, {
    'id': 7,
    'username': 'swarburton6',
    'first_name': 'Sharity',
    'last_name': 'Warburton',
    'profile_img': 'https://robohash.org/sitquiatotam.png?size=128x128&set=set1',
    'comment': 'Donec semper sapien a libero. Nam dui.',
    'timestamp': '1478405248',
  }, {
    'id': 8,
    'username': 'fbarthelme7',
    'first_name': 'Francene',
    'last_name': 'Barthelme',
    'profile_img': 'https://robohash.org/modinihilarchitecto.png?size=128x128&set=set1',
    'comment': 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
    'timestamp': '1477319426',
  }, {
    'id': 9,
    'username': 'rstevings8',
    'first_name': 'Rudy',
    'last_name': 'Stevings',
    'profile_img': 'https://robohash.org/estcupiditatequi.png?size=128x128&set=set1',
    'comment': 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.',
    'timestamp': '1494390123',
  }, {
    'id': 10,
    'username': 'hgosswell9',
    'first_name': 'Husein',
    'last_name': 'Gosswell',
    'profile_img': 'https://robohash.org/natusvoluptatesunde.png?size=128x128&set=set1',
    'comment': 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.',
    'timestamp': '1482142230',
  }, {
    'id': 11,
    'username': 'sbelvina',
    'first_name': 'Siegfried',
    'last_name': 'Belvin',
    'profile_img': 'https://robohash.org/sintquisquamfacere.png?size=128x128&set=set1',
    'comment': 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    'timestamp': '1478575051',
  }, {
    'id': 12,
    'username': 'nnorwoodb',
    'first_name': 'Netti',
    'last_name': 'Norwood',
    'profile_img': 'https://robohash.org/ametautaut.png?size=128x128&set=set1',
    'comment': 'Duis ac nibh.',
    'timestamp': '1492350987',
  }, {
    'id': 13,
    'username': 'aberstonc',
    'first_name': 'Aidan',
    'last_name': 'Berston',
    'profile_img': 'https://robohash.org/similiquequislabore.png?size=128x128&set=set1',
    'comment': 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    'timestamp': '1474481823',
  }, {
    'id': 14,
    'username': 'kkillingsworthd',
    'first_name': 'Kaylil',
    'last_name': 'Killingsworth',
    'profile_img': 'https://robohash.org/quasioccaecatised.png?size=128x128&set=set1',
    'comment': 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    'timestamp': '1481144505',
  }, {
    'id': 15,
    'username': 'bellicke',
    'first_name': 'Brew',
    'last_name': 'Ellick',
    'profile_img': 'https://robohash.org/praesentiumdoloresdeleniti.png?size=128x128&set=set1',
    'comment': 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',
    'timestamp': '1472759706',
  }]

export const TEST_NOTIFICATIONS = [
  {
    'id': '11fc9fff-e005-4b4d-9e35-c18cbba2d1a8',
    'message': 'Bought a ticket for "Party fest"',
    'username': 'iwoodard0',
    'profile_img': 'https://robohash.org/reprehenderitametpariatur.bmp?size=50x50&set=set1',
    'timestamp': '1496826442',
  }, {
    'id': '16a93662-7b45-4c9e-aff9-e4a455179ab8',
    'message': 'Followed you',
    'username': 'lwagerfield1',
    'profile_img': 'https://robohash.org/autacupiditate.jpg?size=50x50&set=set1',
    'timestamp': '1496845038',
  }, {
    'id': '8cc80bde-6adb-4307-a6b3-028c4bbbd579',
    'message': 'Followed you',
    'username': 'vbegg2',
    'profile_img': 'https://robohash.org/dolorumsequieos.bmp?size=50x50&set=set1',
    'timestamp': '1496716095',
  }, {
    'id': '77dfdee4-e3df-4985-8bbc-6f7d36c432a0',
    'message': 'Followed you',
    'username': 'nvalentine3',
    'profile_img': 'https://robohash.org/oditrerumet.bmp?size=50x50&set=set1',
    'timestamp': '1496383957',
  }, {
    'id': 'ce89f930-adef-4fb8-908c-fab417be48ed',
    'message': 'Bought a ticket for "Party fest"',
    'username': 'zhundall4',
    'profile_img': 'https://robohash.org/voluptasfacilisdoloremque.png?size=50x50&set=set1',
    'timestamp': '1496520065',
  }, {
    'id': 'eae55a96-ae46-465d-8133-3b7b4d57c11a',
    'message': 'Bought a ticket for "Party fest"',
    'username': 'gswayland5',
    'profile_img': 'https://robohash.org/utquisrepellendus.bmp?size=50x50&set=set1',
    'timestamp': '1496790861',
  }, {
    'id': '5023b73a-4b2a-483a-a125-7144b8729f37',
    'message': 'Bought a ticket for "Party fest"',
    'username': 'cguisot6',
    'profile_img': 'https://robohash.org/solutaconsecteturet.bmp?size=50x50&set=set1',
    'timestamp': '1496754103',
  }, {
    'id': '012a34c2-5faa-4167-88a0-4a5b03c6e613',
    'message': 'Bought a ticket for "Party fest"',
    'username': 'ttaree7',
    'profile_img': 'https://robohash.org/fugitetarchitecto.jpg?size=50x50&set=set1',
    'timestamp': '1496802610',
  }, {
    'id': '8e5a2c20-29ec-482a-926d-86cb0c605ec4',
    'message': 'Bought a ticket for "Party fest"',
    'username': 'jwiggans8',
    'profile_img': 'https://robohash.org/laborumdoloremat.png?size=50x50&set=set1',
    'timestamp': '1496689555',
  }, {
    'id': '8e85b68e-0eeb-4a41-a9d8-9c163fd72981',
    'message': 'Bought a ticket for "Party fest"',
    'username': 'njorez9',
    'profile_img': 'https://robohash.org/iddoloremvoluptatem.jpg?size=50x50&set=set1',
    'timestamp': '1496897155',
  }]

export const TEST_PENDING_APPROVAL = [
  {
    'id': 1,
    'first_name': 'Jephthah',
    'last_name': 'Sinnie',
    'username': 'jsinnie0',
    'profile_img': 'https://robohash.org/consequuntureummolestiae.jpg?size=50x50&set=set1',
    status: 2,
  }, {
    'id': 2,
    'first_name': 'Moira',
    'last_name': 'Aizkovitch',
    'username': 'maizkovitch1',
    'profile_img': 'https://robohash.org/quasblanditiisdolores.png?size=50x50&set=set1',
    status: 1,
  }, {
    'id': 3,
    'first_name': 'Hedy',
    'last_name': 'Mapledoram',
    'username': 'hmapledoram2',
    'profile_img': 'https://robohash.org/molestiaeoccaecatirerum.png?size=50x50&set=set1',
    status: 1,
  }, {
    'id': 4,
    'first_name': 'Pyotr',
    'last_name': 'Tassel',
    'username': 'ptassel3',
    'profile_img': 'https://robohash.org/voluptatearchitectoassumenda.png?size=50x50&set=set1',
    status: 1,
  }, {
    'id': 5,
    'first_name': 'Vittorio',
    'last_name': 'Piens',
    'username': 'vpiens4',
    'profile_img': 'https://robohash.org/impeditinventoreillum.bmp?size=50x50&set=set1',
    status: 1,
  }, {
    'id': 6,
    'first_name': 'Olly',
    'last_name': 'Davids',
    'username': 'odavids5',
    'profile_img': 'https://robohash.org/abquiaenim.jpg?size=50x50&set=set1',
    status: 1,
  }]