# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'Wattz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Firebase
  pod 'Google/SignIn'
  pod 'GooglePlaces', '2.2.0'
  pod 'GoogleMaps', '2.2.0'
  pod 'GooglePlacePicker', '2.2.0'
  pod 'Firebase', '4.3.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'


  # Third-party libs
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

end
