fastlane_version '2.64.1'

before_all do
  ensure_git_branch
  #ensure_git_status_clean
  #git_pull
end

platform :ios do
   desc 'Build the iOS application.'
   lane :build do
     increment_build_number(xcodeproj: './ios/Wattz.xcodeproj')
     gym(scheme: 'Wattz', workspace: './ios/Wattz.xcworkspace', export_method: 'enterprise', suppress_xcode_output: true)
   end
end

platform :android do
  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end
end
